<?php

namespace App\Models;

use Backpack\CRUD\app\Models\Traits\CrudTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;

class Order extends Model
{
    use CrudTrait;

    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    protected $table = 'orders';
    // protected $primaryKey = 'id';
    // public $timestamps = false;
    protected $guarded = ['id'];
    // protected $fillable = [];
    // protected $hidden = [];
    // protected $dates = [];

    /*
    |--------------------------------------------------------------------------
    | FUNCTIONS
    |--------------------------------------------------------------------------
    */

    public function getOrderStatus(){
        $order_status = [
            PROCESSING => "處理中",
            COMPLETED => "已完成",
            CANCELED => "已取消"];

        return $order_status[$this->status];
    }

    public function getPaymentStatus(){
        $payment_status = [
            UNPAID => "未付款",
            PAID => "已付款",
            REFUNDING => "退款中",
            REFUNDED => "已退款"];

        return $payment_status[$this->payment_status];
    }


    public function getDeliveryStatus(){
        $delivery_status = [
            WAITING => "待出貨",
            DELIVERING => " 運送中",
            DELIVERED => " 已送達"];

        return $delivery_status[$this->delivery_status];
    }

    public function getPaymentMethod(){
        $payment_method = [
            "ecpay" => "信用卡付款",
            "cod" => "現場付款",
        ];
        return $payment_method[$this->payment_method];
    }

    public function totalSales(){

    }


    /*
    |--------------------------------------------------------------------------
    | RELATIONS
    |--------------------------------------------------------------------------
    */

    public function user(){
        return $this->belongsTo("App\Models\User");
    }

    public function items(){
        return $this->hasMany("App\Models\OrderItem");
    }

    /*
    |--------------------------------------------------------------------------
    | SCOPES
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | ACCESSORS
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | MUTATORS
    |--------------------------------------------------------------------------
    */

    public function getPaymentTypeAttribute(){
        $payment_type = [
            "Credit_CreditCard" => "信用卡"
        ];
        return isset($payment_type[$this->attributes["payment_type"]]) ? $payment_type[$this->attributes["payment_type"]] : "";
    }

    public function getPnameAttribute(){
        $product_name = [];
        foreach ($this->items as $item){
            $product_name[] = $item->product_name;
        }

        return implode(", ", $product_name);
    }

    public function getShipaddrAttribute(){
        return "{{ $this->shipping_name }},
    {{ $this->shipping_phone }}
    {{ $this->shipping_zipcode }}
    {{ $this->shipping_address }} {{ $this->shipping_address2 }}
    {{ $this->state }}, {{ $this->country }}";
    }

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub

        static::updated(function ($order){
            if($order->user){

                if($order->user){
                    $order->user->is_vip = $order->user->consume >= 4000;
                }

                //Reward
                $reward_point = new UserPoint([
                    "user_id" => $order->user->id,
                    "amount" => $order->sub_total,
                    "created_at" => now(),
                    "notes" => "消費積分"
                ]);

                $reward_point->save();
                $order->user->points += $reward_point->amount;

                Log::info("Reward {$reward_point->amount} for user #{$order->user->id} on #{$order->order_id}");

                $order->user->save();
            }
        });
    }


}
